Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -76,11 +76,9 @@ jobs:
       with:
         category: "/language:${{matrix.language}}"
         
-    - name: Check for Issues  
-      if: always()   
-      run: |  
-       if grep -q 'critical' results.sarif || grep -q 'high' results.sarif;  
-       then  
-         echo 'CodeQL found issues!'  
-         exit 1   
-       fi 
+    - name: Check for high or critical issues
+      run: |
+        if [ $(jq '.[0].alertSeverity == "high" or .[0].alertSeverity == "critical"' ${{ steps.codeql-results.outputs.results }}) = true ]; then
+          echo "High or critical issues found. Failing the build."
+          exit 1
+        fi
